# mode اكتر تكرار names
# mean >> average numbers

In [2]:
import pandas as pd
dp = pd.read_csv('/content/students.csv')
dp.head(10)
dp.tail()
dp.shape
dp.info()
dp.describe()
dp.columns
dp.dtypes
dp[["Age","Name"]]
dp.iloc[0:2,0:9]      #row then col
dp.iloc[0:2,0:]      #row then col     index onlt
dp.loc[:,['Name','Age']]    #index or name
dp[dp['GPA']>2.98]     #Filtering
dp.sort_values('Salary' , ascending=True)
dp.sort_values('Salary' , ascending=False)
dp.isnull().sum()
dp['Salary']=dp['Salary'].fillna(dp['Salary'].mean())
dp['GPA']=dp['GPA'].fillna(dp['GPA'].mean())
dp.isnull().sum()
dp.duplicated().sum()
dp[dp.duplicated]
dp = dp.drop_duplicates()
dp.groupby('Department')['Salary'].agg('mean','max','min')
dp.pivot_table(values='Salary',index='Department',aggfunc='mean')
dp['Bonus']= dp['Salary'].apply(lambda x:x*4)
dp['Gender_code']= dp['Gender'].map({'Male': 0,'Female': 1})
dp[['Gender','Gender_code']].head()
dp['Passed']=dp['Passed'].replace({'Yes':'Pass','No':'Fail'})
dp[['Passed']].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          41 non-null     int64
 1   Name        41 non-null     object
 2   Age         41 non-null     int64
 3   Gender      41 non-null     object
 4   Department  41 non-null     object
 5   GPA         40 non-null     float64
 6   Salary      40 non-null     float64
 7   City        41 non-null     object
 8   Attendance  41 non-null     int64
 9   Passed      41 non-null     object
dtypes: float64(2), int64(3), object(5)
memory usage: 3.3+ KB

  Passed
0   Fail
1   Pass
2   Fail
3   Pass
4   Pass

In [8]:
grades = pd.read_csv('grades.csv')
# pd.merge(dp,grades,on='ID').head()
clean_students = pd.merge(dp, grades, on='ID')
clean_students.to_csv('clean_students.csv', index=False)
clean_students.head()
!ls

clean_students.csv  drive  grades.csv  sample_data  students.csv

In [9]:
import base64
from IPython.display import HTML

# Read the file data
with open('clean_students.csv', 'r') as f:
    csv_data = f.read()

# Encode to base64 to build a direct browser link
b64 = base64.b64encode(csv_data.encode()).decode()
href = f'<a href="data:file/csv;base64,{b64}" download="clean_students.csv" style="font-size: 16px; font-weight: bold; color: #007acc;">👉 Click Here to Download clean_students.csv 👈</a>'

# Display the link
HTML(href)

In [10]:
file_id = '18Aie7PXX77qZj1mFHp2YXw-gzBstu19p'
url = f"https://drive.google.com/uc?export=download&id={file_id}"

In [11]:
df = pd.read_csv(url)
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished